AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6 # really 2.4, but 2.6 is lowest supported by rubocop

Layout/DotPosition:
  Enabled: false
Metrics/BlockLength:
  Exclude: ['test/**/*.rb']
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/SelectByRegexp:
  Enabled: false
Style/StringLiterals:
  Enabled: false
