AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6 # really 2.4, but 2.6 is lowest supported by rubocop

# warning! changes here might break specs that test config evaluation.
Gemspec/RequireMFA:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Metrics/BlockLength:
  Exclude: ['spec/**/*.rb']
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/SelectByRegexp:
  Enabled: false
Style/StringLiterals:
  Enabled: false
